import SwiftUI

/// Lightweight SF Symbol wrappers used throughout the workspace.
/// We rely on a small, consistent set of monochrome line icons.
public enum MonoIcon {
    public static let chevronRight = "chevron.right"
    public static let chevronDown = "chevron.down"
    public static let chevronUp = "chevron.up"
    public static let folder = "folder"
    public static let folderOpen = "folder.fill"
    public static let doc = "doc"
    public static let docText = "doc.text"
    public static let search = "magnifyingglass"
    public static let plus = "plus"
    public static let close = "xmark"
    public static let check = "checkmark"
    public static let circle = "circle"
    public static let circleFill = "circle.fill"
    public static let circleDot = "circle.dashed"
    public static let arrow = "arrow.right"
    public static let branch = "arrow.triangle.branch"
    public static let terminal = "terminal"
    public static let play = "play"
    public static let refresh = "arrow.clockwise"
    public static let settings = "gearshape"
    public static let sparkles = "sparkles"
    public static let paperPlane = "paperplane"
    public static let sidebar = "sidebar.left"
    public static let inspector = "sidebar.right"
    public static let panel = "rectangle.split.3x1"
    public static let command = "command"
    public static let globe = "globe"
    public static let github = "network"   // SF Symbol approximating git/network; we draw the GitHub logo separately where required
    public static let build = "hammer"
    public static let test = "checkmark.seal"
    public static let warning = "exclamationmark.triangle"
    public static let error = "xmark.octagon"
    public static let info = "info.circle"
    public static let lock = "lock"
    public static let key = "key"
    public static let trash = "trash"
    public static let pencil = "pencil"
    public static let eye = "eye"
    public static let download = "arrow.down.to.line"
    public static let upload = "arrow.up.from.line"
    public static let pull = "arrow.down.circle"
    public static let push = "arrow.up.circle"
    public static let commit = "arrow.triangle.merge"
    public static let diff = "square.split.2x1"
    public static let history = "clock.arrow.circlepath"
    public static let tag = "tag"
    public static let bookmark = "bookmark"
    public static let folderPlus = "folder.badge.plus"
    public static let docPlus = "doc.badge.plus"
    public static let copy = "doc.on.doc"
    public static let move = "arrow.left.and.right"
    public static let sort = "arrow.up.arrow.down"
    public static let filter = "line.3.horizontal.decrease"
    public static let model = "cpu"
    public static let agent = "person.crop.circle"
    public static let agentGroup = "person.3"
    public static let stack = "square.stack.3d.up"
    public static let layers = "layer.group"
    public static let phone = "iphone"
    public static let tablet = "ipad"
    public static let laptop = "laptopcomputer"
    public static let desktop = "desktopcomputer"
    public static let palette = "paintpalette"
    public static let font = "textformat"
    public static let keyboard = "keyboard"
    public static let mouse = "computermouse"
    public static let pencilTool = "pencil.tip"
    public static let link = "link"
    public static let clip = "paperclip"
    public static let image = "photo"
    public static let camera = "camera"
    public static let mic = "mic"
    public static let stop = "stop"
    public static let pause = "pause"
    public static let step = "forward"
    public static let bolt = "bolt"
    public static let clock = "clock"
    public static let calendar = "calendar"
    public static let bell = "bell"
    public static let star = "star"
    public static let heart = "heart"
    public static let chart = "chart.bar"
    public static let list = "list.bullet"
    public static let grid = "square.grid.2x2"
    public static let card = "rectangle"
    public static let menu = "line.3.horizontal"
    public static let share = "square.and.arrow.up"
    public static let more = "ellipsis"
    public static let question = "questionmark.circle"
    public static let shield = "shield"
    public static let eyeOff = "eye.slash"
    public static let external = "arrow.up.right.square"
}

public extension Image {
    static func mono(_ name: String) -> Image {
        Image(systemName: name)
    }
}
