import Foundation

/// Installs functional starter templates when a new project is created.
public enum TemplateInstaller {
    public static func install(template: ProjectTemplate, at url: URL, name: String) throws {
        let fm = FileManager.default
        switch template {
        case .empty:
            try "".write(to: url.appendingPathComponent("README.md"), atomically: true, encoding: .utf8)
        case .swiftUI:
            try write(url, "AdventureCoderApp.swift", """
            import SwiftUI

            @main
            struct \(name.pascalCase)App: App {
                var body: some Scene {
                    WindowGroup {
                        ContentView()
                    }
                }
            }
            """)
            try write(url, "ContentView.swift", """
            import SwiftUI

            struct ContentView: View {
                var body: some View {
                    VStack(spacing: 16) {
                        Image(systemName: "sparkles")
                            .font(.system(size: 48))
                        Text("\(name.pascalCase)")
                            .font(.title)
                        Text("Built with Adventure Coder.")
                            .foregroundStyle(.secondary)
                    }
                    .padding()
                }
            }

            #Preview {
                ContentView()
            }
            """)
            try write(url, "README.md", "# \(name)\n\nA SwiftUI app generated by Adventure Coder.\n")
        case .iosApp:
            try write(url, "AppDelegate.swift", """
            import UIKit

            @main
            class AppDelegate: UIResponder, UIApplicationDelegate {
                func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
                    return true
                }
            }
            """)
            try write(url, "SceneDelegate.swift", """
            import UIKit

            class SceneDelegate: UIResponder, UIWindowSceneDelegate {
                var window: UIWindow?
                func scene(_ scene: UIScene, willConnectTo session: UISceneSession, options connectionOptions: UIScene.ConnectionOptions) {
                    guard let scene = scene as? UIWindowScene else { return }
                    let window = UIWindow(windowScene: scene)
                    window.rootViewController = UIHostingController(rootView: ContentView())
                    window.makeKeyAndVisible()
                    self.window = window
                }
            }

            import SwiftUI
            struct ContentView: View {
                var body: some View {
                    Text("Hello, Adventure Coder!")
                        .padding()
                }
            }
            """)
        case .react:
            try write(url, "index.html", """
            <!doctype html>
            <html lang="en">
              <head>
                <meta charset="UTF-8" />
                <meta name="viewport" content="width=device-width, initial-scale=1.0" />
                <title>\(name)</title>
              </head>
              <body>
                <div id="root"></div>
                <script type="module" src="/src/main.tsx"></script>
              </body>
            </html>
            """)
            try write(url, "package.json", """
            {
              "name": "\(name)",
              "version": "0.0.0",
              "type": "module",
              "scripts": {
                "dev": "vite",
                "build": "vite build",
                "preview": "vite preview"
              },
              "dependencies": {
                "react": "^18.3.1",
                "react-dom": "^18.3.1"
              },
              "devDependencies": {
                "@types/react": "^18.3.3",
                "@types/react-dom": "^18.3.0",
                "typescript": "^5.4.5",
                "vite": "^5.3.1"
              }
            }
            """)
            try write(url, "tsconfig.json", """
            {
              "compilerOptions": {
                "target": "ES2020",
                "useDefineForClassFields": true,
                "lib": ["ES2020", "DOM", "DOM.Iterable"],
                "module": "ESNext",
                "skipLibCheck": true,
                "moduleResolution": "bundler",
                "jsx": "react-jsx",
                "strict": true
              },
              "include": ["src"]
            }
            """)
            try fm.createDirectory(at: url.appendingPathComponent("src"), withIntermediateDirectories: true)
            try write(url, "src/main.tsx", """
            import React from 'react'
            import ReactDOM from 'react-dom/client'
            import App from './App'

            ReactDOM.createRoot(document.getElementById('root')!).render(<App />)
            """)
            try write(url, "src/App.tsx", """
            export default function App() {
              return (
                <main style={{ fontFamily: 'system-ui', padding: 24 }}>
                  <h1>\(name)</h1>
                  <p>Built with Adventure Coder.</p>
                </main>
              )
            }
            """)
        case .web, .html:
            try write(url, "index.html", """
            <!doctype html>
            <html lang="en">
              <head>
                <meta charset="UTF-8" />
                <meta name="viewport" content="width=device-width, initial-scale=1.0" />
                <title>\(name)</title>
                <link rel="stylesheet" href="styles.css" />
              </head>
              <body>
                <main>
                  <h1>\(name)</h1>
                  <p>Built with Adventure Coder.</p>
                </main>
                <script src="script.js"></script>
              </body>
            </html>
            """)
            try write(url, "styles.css", """
            :root {
              color-scheme: light;
              --fg: #111;
              --bg: #fff;
            }
            body {
              margin: 0;
              font-family: -apple-system, system-ui, sans-serif;
              color: var(--fg);
              background: var(--bg);
            }
            main {
              max-width: 720px;
              margin: 0 auto;
              padding: 48px 24px;
            }
            """)
            try write(url, "script.js", """
            console.log('\(name) ready');
            """)
        case .javascript:
            try write(url, "package.json", """
            {
              "name": "\(name)",
              "version": "1.0.0",
              "type": "module",
              "main": "index.js",
              "scripts": { "start": "node index.js" }
            }
            """)
            try write(url, "index.js", """
            console.log('\(name) ready');
            """)
        case .python:
            try write(url, "requirements.txt", "")
            try write(url, "main.py", """
            def main():
                print("\(name) ready")

            if __name__ == "__main__":
                main()
            """)
        case .rust:
            try write(url, "Cargo.toml", """
            [package]
            name = "\(name)"
            version = "0.1.0"
            edition = "2021"

            [dependencies]
            """)
            try fm.createDirectory(at: url.appendingPathComponent("src"), withIntermediateDirectories: true)
            try write(url, "src/main.rs", """
            fn main() {
                println!("\(name) ready");
            }
            """)
        }

        // Always create a gitignore appropriate for the template
        try write(url, ".gitignore", gitignore(for: template))
    }

    private static func write(_ root: URL, _ path: String, _ content: String) throws {
        let url = root.appendingPathComponent(path)
        try FileManager.default.createDirectory(at: url.deletingLastPathComponent(), withIntermediateDirectories: true)
        try content.data(using: .utf8)?.write(to: url, options: .atomic)
    }

    private static func gitignore(for template: ProjectTemplate) -> String {
        var lines: [String] = [".DS_Store", "*.log", "build/", "DerivedData/"]
        switch template {
        case .swiftUI, .iosApp, .empty:
            lines.appendContents(["*.xcuserstate", "xcuserdata/", "*.xcworkspace/xcuserdata/"])
        case .react, .web, .html, .javascript:
            lines.appendContents(["node_modules/", "dist/", ".env"])
        case .python:
            lines.appendContents(["__pycache__/", "*.pyc", ".venv/", "venv/"])
        case .rust:
            lines.appendContents(["target/", "Cargo.lock"])
        }
        return lines.joined(separator: "\n") + "\n"
    }
}

private extension Array {
    mutating func appendContents(_ items: [Element]) {
        append(contentsOf: items)
    }
}

private extension String {
    var pascalCase: String {
        let parts = split(whereSeparator: { !$0.isLetter && !$0.isNumber })
        return parts.map { $0.prefix(1).uppercased() + $0.dropFirst().lowercased() }.joined()
    }
}
